version: 2.1
jobs:
  build_and_test:
    parameters:
      compiler:
        description: C++ compiler to build with
        type: string
      standard:
        description: C++ standard to build with
        type: string
      mode:
        description: mode to build and test with
        type: string
    machine:
      image:  ubuntu-2204:2023.04.2
    resource_class: large
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: echo 'docker run --pids-limit -1 --security-opt seccomp=unconfined --network host --user "$(id -u):$(id -g)" --rm -v $PWD:$PWD -w $PWD  docker.io/scylladb/seastar-toolchain:2023-08-13 "$@"' > run; chmod +x run
      - run: ./run ./configure.py --compiler << parameters.compiler >> --c++-standard << parameters.standard >>
      - when:
          condition:
            equal: [ dev, << parameters.mode >> ]
          steps:
            - run: ./run ninja -C build/<< parameters.mode >> checkheaders
      - run: ./run ninja -C build/<< parameters.mode >>
      - run: ./run ./test.py --mode=<< parameters.mode >>

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              compiler: ["clang++-17", "g++-13"]
              standard: ["20", "17"]
              mode: ["dev", "debug", "release"]
